// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWwWZiUmVKbiQG34QZtfyWxjHKjH3kfY',
    appId: '1:230393683237:web:e95401a0f18b7de75b0ecc',
    messagingSenderId: '230393683237',
    projectId: 'thom-apps-9103c',
    authDomain: 'thom-apps-9103c.firebaseapp.com',
    databaseURL: 'https://thom-apps-9103c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thom-apps-9103c.appspot.com',
    measurementId: 'G-3KT477GF1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Swma95Vp0vI6IytcgZ7UqTapjw1VTF8',
    appId: '1:230393683237:android:96cae7efd51b04575b0ecc',
    messagingSenderId: '230393683237',
    projectId: 'thom-apps-9103c',
    databaseURL: 'https://thom-apps-9103c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thom-apps-9103c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOpkqtu79_oSX5BOrLgKzpRNT6zIMwuos',
    appId: '1:230393683237:ios:d7066e9635edf2e25b0ecc',
    messagingSenderId: '230393683237',
    projectId: 'thom-apps-9103c',
    databaseURL: 'https://thom-apps-9103c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thom-apps-9103c.appspot.com',
    iosClientId: '230393683237-vtiu3k64q6a81mkvb68b6sdmq4vaviju.apps.googleusercontent.com',
    iosBundleId: 'com.example.thomapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOpkqtu79_oSX5BOrLgKzpRNT6zIMwuos',
    appId: '1:230393683237:ios:d7066e9635edf2e25b0ecc',
    messagingSenderId: '230393683237',
    projectId: 'thom-apps-9103c',
    databaseURL: 'https://thom-apps-9103c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thom-apps-9103c.appspot.com',
    iosClientId: '230393683237-vtiu3k64q6a81mkvb68b6sdmq4vaviju.apps.googleusercontent.com',
    iosBundleId: 'com.example.thomapps',
  );
}
